apiVersion: v1
kind: ConfigMap
metadata:
  name: email-filter-config
data:
  app_config.py: |
    # Configurações da aplicação
    GRADIO_CONFIG = {
        "server_name": "0.0.0.0",
        "server_port": 7860,
        "share": False,
        "debug": False
    }
    
    MODEL_CONFIG = {
        "max_features": 5000,
        "test_size": 0.2,
        "random_state": 42
    }
    
    DATASET_CONFIG = {
        "default_size": 1000,
        "categories": ["importante", "promocional", "spam", "pessoal"]
    }
